social_site/core/urls.py
from django.urls import path

from . import views
#il punto perchè importiamo dallo stesso modulo (core)


urlpatterns = [
    path('', views.HomeView.as_view(), name="homepage"),
    path('users/', views.UserList.as_view(), name="user_list"),
    path('user/<str:username>/', views.user_profile_view, name="user_profile"),
    path('cerca/', views.cerca, name="funzione_cerca"),

]

social_site/social_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forum/', include('forum.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_site/core/models.py
from django.db import models

# Create your models here.

social_site/forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from math import ceil

# Create your models here.

class Sezione(models.Model):
    """
    Modello generico di una sezione del Forum.
    Le sezioni dividono il sito per categorie di discussione.
    Ciascuna sezione contiene svariate Discussioni.
    Le sezioni vengono create dagli amministratori del sito.
    """

    nome_sezione = models.CharField(max_length=80)
    descrizione = models.CharField(max_length=150, blank=True, null=True)
    logo_sezione = models.ImageField(blank=True, null=True)

    class Meta:
        verbose_name = "Sezione"
        verbose_name_plural = "Sezioni"

    def __str__(self):
        return self.nome_sezione

    def get_absolute_url(self):
        return reverse("sezione_view", kwargs={"pk": self.pk})

    def get_last_discussions(self):
        """Restituisce le ultime due discussioni della sezione, ordinate per data"""
        return Discussione.objects.filter(sezione_appartenenza=self).order_by("-data_creazione")[:2]

    def get_number_of_posts_in_section(self):
        """Restituisce il numero di post totali presenti in una istanza di sezione"""
        return Post.objects.filter(discussione__sezione_appartenenza=self).count()


class Discussione(models.Model):
    """
    Il modello di una singola discussione del forum.
    Ogni discussione "fa parte" di una specifica sezione.
    Le discussioni possono essere create da tutti gli utenti del sito.
    """

    objects = None
    titolo = models.CharField(max_length=120)
    data_creazione = models.DateTimeField(auto_now_add=True)
    autore_discussione = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="discussioni"
    )
    sezione_appartenenza = models.ForeignKey(Sezione, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Discussione"
        verbose_name_plural = "Discussioni"

    def __str__(self):
        return self.titolo

    def get_absolute_url(self):
        return reverse("visualizza_discussione", kwargs={"pk": self.pk})

    def get_n_pages(self):
        """
        Restituisce il numero di pagina presenti in una istanza di Discussione.
        math.ceil https://docs.python.org/3.6/library/math.html#math.ceil
        restituisce il numero intero successivo al float passato come parametro (es 3.1 ==> 4)
        o restituisce lo stesso numero se intero
        """
        posts_discussione = self.post_set.count()
        n_pagine = math.ceil(posts_discussione / 5)
        return n_pagine

class Post(models.Model):
    objects = None
    autore_post = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    contenuto = models.TextField()
    data_creazione = models.DateTimeField(auto_now_add=True)
    discussione = models.ForeignKey(Discussione, on_delete=models.CASCADE)

    def __str__(self):
        return self.autore_post.username

    class Meta:
        verbose_name="Post"
        verbose_name_plural="Posts"

social_site/core/views.py
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.list import  ListView
from forum.models import Discussione, Sezione, Post


#get_object_or_404 prende un oggetto(nel caso pk), che se fosse presente ce lo mostra, altrimenti ci mostra errore
# Create your views here.

# def homepage(request):
#     return render(request,'core/homepage.html')
class HomeView (ListView):
    queryset = Sezione.objects.all ()
    template_name = 'core/homepage.html'
    context_object_name = "lista_sezioni"




class UserList (LoginRequiredMixin,ListView):
    model = User
    template_name = "core/users.html"


def user_profile_view (request, username):
    user= get_object_or_404(User, username=username)
    discussioni_utente = Discussione.objects.filter(autore_discussione=user).order_by("-pk")
    context = {"user": user, "discussioni_utente": discussioni_utente}
    return render (request, "core/user_profile.html", context)


def cerca (request):

    if "q" in request.GET:
        querystring = request.GET.get ("q")
        if len(querystring) == 0:
            return redirect("/cerca/")
        discussioni = Discussione.objects.filter(titolo__icontains=querystring)
        posts = Post.objects.filter(contenuto__icontains=querystring)
        users = User.objects.filter(username__icontains=querystring)
        context = {"discussioni": discussioni, "posts": posts, "users": users}
        return render(request,"core/cerca.html", context)
    else:
        return (request,"core/cerca.html")

social_site/core/templates/core/cerca.html
{% extends 'base.html' %}

{% block head_title %}{{ block.super }} - Cerca nel Forum{% endblock head_title %}

{% block content %}
<h1 class="mt-3">Risultati della Ricerca</h1>
<hr>
<div class="row mt-3">
    <div class="col-4">
        <h5><strong>Posts</strong></h5>
        <hr>
        {% if posts %}
            {% for post in posts %}
                <p>{{ post.contenuto|truncatewords:"10" }}</p>
                <p class="mb-0">by <a href="{% url 'user_profile' username=post.autore_post.username %}">@{{ post.autore_post.username }}</a></p>
                <p>in <a href="{{ post.discussione.get_absolute_url }}">{{ post.discussione.titolo }}</a></p>
                <hr>
            {% endfor %}
        {% else %}
            <p>---</p>
        {% endif %}
    </div>
    <div class="col-4">
        <h5><strong>Discussioni</strong></h5>
        <hr>
        {% if discussioni %}
            {% for discussione in discussioni %}
                <p>¤ <a href="{{ discussione.get_absolute_url }}">{{ discussione.titolo }}</a></p>
            {% endfor %}
        {% else %}
            <p>---</p>
        {% endif %}
    </div>
    <div class="col-4">
        <h5><strong>Utenti</strong></h5>
        <hr>
        {% if users %}
            {% for utente in users %}
                <p><a href="{% url 'user_profile' username=utente.username %}">@{{ utente }}</a></p>
            {% endfor %}
        {% else %}
            <p>---</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

social_site/core/templates/core/homepage.html
{% extends 'base.html' %}

{% block content %}

{% if request.user.is_staff %}
    <div class="card-body ps-0 pb-0">
        <a class="btn btn-sm btn-danger" href="{% url 'crea_sezione' %}">Crea Sezione</a>
    </div>
{% endif %}

{% for sezione in lista_sezioni %}
    <div class="card my-3">
        <div class="card-header">
            <h5><a href="{{ sezione.get_absolute_url }}"><strong>{{ sezione.nome_sezione }}</strong></a></h5>
            <p class="mb-0">{{ sezione.descrizione }}</p>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-3">
                    <img src="{{ sezione.logo_sezione.url }}" style="max-width:100%">
                    <p>Discussioni Totali: {{ sezione.discussione_set.count }}
                    <br>Messaggi Totali: {{ sezione.get_number_of_posts_in_section }}</p>
                </div>
                <div class="col-lg-9">
                    <p>Ultime Discussioni</p>
                    <table class="table table-hover">
                        <tbody>
                            {% for discussione in sezione.get_last_discussions.all %}
                                <tr class="row">
                                    <td class="col-lg-7 col-6">
                                        <a href="{% url 'visualizza_discussione' pk=discussione.pk %}">{{ discussione.titolo }}</a>
                                    </td>
                                    <td class="col-lg-3 col-3">
                                        by <a href="{% url 'user_profile' username=discussione.autore_discussione.username %}">{{ discussione.autore_discussione }}</a>
                                    </td>
                                    <td class="col-lg-2 col-3">
                                        posts: {{ discussione.post_set.count }}</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock content %}

social_site/core/templates/core/user_profile.html
{% extends 'base.html' %}

{% block head_title %}{{ block.super }} - {{ user }}{% endblock head_title %}

{% block content %}
<div class="row mt-3">
    <div class="col-4">
        <div class="card my-2">
            <div class="card-header">
                <h4>{% if request.user == user %}Il Tuo {% endif %}Profilo Utente</h4>
            </div>
            <div class="card-body">
                <p class="lead">@{{ user }}</p>
                <p class="mb-0">Iscrizione: {{ user.date_joined|date:"d M Y" }}</p>
                <p class="mb-0">Discussioni: {{ user.discussioni.count }}</p>
                <p class="mb-0">Posts: {{ user.posts.count }}</p>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>

    <div class="col-8">
        <div class="card my-2">
            <div class="card-header">
                <h4>Discussioni</h4>
            </div>
            <div class="card-body">
                {% for discussione in discussioni_utente %}
                    <a href="{{ discussione.get_absolute_url }}">{{ discussione.titolo }}</a>
                    <p class="text-muted">{{ discussione.sezione_appartenenza }}</p>
                {% empty %}
                    {% if request.user != user %}
                        <p>{{ user }} non ha creato alcuna discussione!</p>
                    {% else %}
                        <p>Non hai creato alcuna discussione! Inizia Subito!</p>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock content %}

social_site/core/templates/core/users.html
{% extends 'base.html' %}

{% block head_title %}{{ block.super }} - Lista Utenti{% endblock head_title %}

{% block content %}

<h2 class="mt-3">Lista Utenti</h2>
<hr>
{% for utente in object_list %}
    {% if forloop.first %}<div class="row">{% endif %}
        <div class="col-lg-4">
            <div class="card my-1 border border-info">
                <div class="card-body py-0">
                    <p class="mb-0">
                        <a href="{% url 'user_profile' username=utente.username %}">
                            <strong>@{{ utente.username }}</strong>
                        </a>
                    </p>
                    Iscrizione: {{ utente.date_joined|date:"d M Y" }}<br>
                    Posts: {{ utente.posts.count }}<br>
                    Discussioni: {{ utente.discussioni.count }}
                </div>
            </div>
        </div>
    {% if forloop.counter|divisibleby:"3" or forloop.last %}</div>{% endif %}
    {% if forloop.counter|divisibleby:"3" and not forloop.last %}<div class="row">{% endif %}
{% endfor %}

{% endblock content %}